-- 1. Crear base de datos y seleccionarla
CREATE DATABASE IF NOT EXISTS SkyRoute;
USE SkyRoute;

-- 2. Configurar modo SQL para permitir fechas cero 
SET sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- 3. Creacion de  tablas 
CREATE TABLE CLIENTE (
    ID_CLIENTE SMALLINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL DEFAULT '',
    CUIT VARCHAR(13) NOT NULL DEFAULT 0,
    MAIL VARCHAR(100) NOT NULL DEFAULT '',
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE DESTINO (
    ID_DESTINO SMALLINT NOT NULL AUTO_INCREMENT,
    PAIS VARCHAR(100) NOT NULL DEFAULT '',
    CIUDAD VARCHAR(100) NOT NULL DEFAULT '',
    COSTO FLOAT NOT NULL DEFAULT 0.00,
    PRIMARY KEY (ID_DESTINO)
);

--  Tabla dependiente
CREATE TABLE VENTA (
    ID_VENTA SMALLINT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE SMALLINT NOT NULL DEFAULT 0,
    ID_DESTINO SMALLINT NOT NULL DEFAULT 0,
    FECHA DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'ACTIVA',
    FECHA_ANULA DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
    MOTIVO_ANULA VARCHAR(200) NOT NULL DEFAULT '',
    PRIMARY KEY (ID_VENTA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DESTINO) REFERENCES DESTINO(ID_DESTINO)
);

